[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python310",
  "python310Packages.pip",
  "python310Packages.setuptools",
  "python310Packages.wheel"
]

[phases.install]
cmds = [
  "npm install",
  "pip3 install --break-system-packages -r requirements.txt"
]